### ISSUE TITLE
Error with /g in v19

### ISSUE THREAD

**Issue by ttk2** [rourke750/CivChat#10]
2014-06-22 09:56:42 [ERROR] null                                                                                                                    [12/9472]│··················
org.bukkit.command.CommandException: Unhandled exception executing command 'g' in plugin CivChat v1.19                                                       │··················
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                  │··················
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                          │··················
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:706) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                 │··················
        at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:984) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]            │··················
        at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:829) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                        │··················
        at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                         │··················
        at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                    │··················
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                            │··················
        at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                         │··················
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                          │··················
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                          │··················
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                          │··················
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                        │··················
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                          │··················
Caused by: java.lang.NullPointerException                                                                                                                    │··················
        at com.untamedears.civchat.ChatManager.GroupChat(ChatManager.java:278) ~[?:?]                                                                        │··················
        at com.untamedears.civchat.Commands.groupchat(Commands.java:447) ~[?:?]                                                                              │··················
        at com.untamedears.civchat.Commands.onCommand(Commands.java:56) ~[?:?]                                                                               │··················
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]                                  │··················
        ... 13 more                                                                                                                                          │··················

> li2014-06-22 09:56:42,607 ERROR An exception occurred processing Appender LogSnoopHandler java.lang.NullPointerException                                    │··················
>         at com.untamedears.MiscLog.LogSnoopHandler.append(LogSnoopHandler.java:66)                                                                           │··················
>         at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)                                                        │··················
>         at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)                                                            │··················
>         at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)                                                                      │··················
>         at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)                                                                      │··················
>         at org.apache.logging.log4j.core.Logger.log(Logger.java:110)                                                                                         │··················
>         at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609)                                                                        │··················
>         at org.bukkit.craftbukkit.v1_7_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:33)                                                          │··················
>         at java.util.logging.Logger.log(Logger.java:616)                                                                                                     │··················
>         at java.util.logging.Logger.doLog(Logger.java:641)                                                                                                   │··················
>         at java.util.logging.Logger.log(Logger.java:730)                                                                                                     │··················
>         at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:990)                                                            │··················
>         at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:829)                                                                        │··················
>         at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28)                                                                         │··················
>         at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:65)                                                                    │··················
>         at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147)                                                                            │··················
>         at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77)                                                                         │··················
>         at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:700)                                                                          │··················
>         at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273)                                                                          │··················
>         at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562)

**Comment by rourke750** [comment]
Stupid conditionals.  Got a new jar for testing.
