### ISSUE TITLE
Stack Exhaustion in reloadConfig

### ISSUE THREAD

**Issue by erocs** [rourke750/CivChat#2]
Probably why reload config doesn't work, as you were saying.

> 23:43:47 [SEVERE] Could not load 'plugins\CivChat.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidPluginException: java.lang.StackOverflowError
>         at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:182)
>         at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
>         at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
>         at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:263)
>         at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:241)
>         at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
>         at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
>         at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:95)
>         at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
>         at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
> Caused by: java.lang.StackOverflowError
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)
>         at com.untamedears.civchat.CivChat.reloadConfig(CivChat.java:38)

**Comment by erocs** [comment]
Fixed in #3
