### ISSUE TITLE
NPE on shutdown

### ISSUE THREAD

**Issue by erocs** [rourke750/CivChat#8]
02:51:04 [SEVERE] Error occurred while disabling CivChat v1.13 (Is it up to date?)
java.lang.NullPointerException
        at java.io.FileOutputStream.<init>(FileOutputStream.java:206)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:165)
        at com.untamedears.civchat.ChatManager.save(ChatManager.java:411)
        at com.untamedears.civchat.CivChat.onDisable(CivChat.java:104)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:401)
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:394)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.disablePlugins(CraftServer.java:300)
        at net.minecraft.server.v1_5_R3.MinecraftServer.stop(MinecraftServer.java:340)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:436)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by rourke750** [comment]
i dont get that error and i just loaded from what i have on github.  Tried
twice after deleting civchat file and not.

**Comment by ibbignerd** [comment]
Looks like manager ChatManager.java and CivChat.java were updated and version number was not. Try getting the most recent version.

**Comment by erocs** [comment]
This was seen when I was restarting CivTest to update Citadel. Maybe the version on CivTest is out of date.

**Comment by rourke750** [comment]
oh, I'll upload all the new stuff to civtest.

**Comment by ibbignerd** [comment]
Is this still an issue?

**Comment by rourke750** [comment]
No, just a bad version on civtest
